use_frameworks!

target 'CPLabelSwitch_Example' do
  pod 'CPLabelSwitch', :path => '../'

  target 'CPLabelSwitch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
